# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Embark | Website Design and Marketing
email: hello@letsembark.ca
facebook: https://www.facebook.com/embarkcanada
instagram: https://www.instagram.com/embarkwebsites
linkedin: https://www.linkedin.com/embarkcanada
twitter: https://www.twitter.com/fevish
description: >- # this means to ignore newlines until "baseurl:"
  Southern Alberta Website Design and Marketing company, we are commited to working with local businesses ranging from Calgary to Medicine Hat.
  Free in-person website consultation. Invite us to your office today!
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://letsembark.ca" # the base hostname & protocol for your site, e.g. http://example.com

host: 0.0.0.0

s3url: https://s3.letsembark.ca/
code: <script type="text/plain" class="language-markup line-numbers">
endcode: </script>
tut: /assets/images/tutorial-images/
# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
    # - jekyll-redirect-from
    #  - jekyll-minifier

defaults:
  -
    scope:
      path:     "assets/**/**/**/**/*.pdf"
    values:
      sitemap:  false    


include: ["_pages", "_redirects"]

sass:
    sass_dir: /assets/stylesheets/_sass
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
